from django.contrib.auth import views as auth_views
from django.urls import path

from . import views


urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('login/', auth_views.LoginView.as_view(
        template_name='accounts/login.html',
        redirect_authenticated_user=True,
    ), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('profile/password/', views.ProfilePasswordChangeView.as_view(), name='profile_password_change'),
    path('profile/edit/', views.AdminProfileUpdateView.as_view(), name='admin_profile_edit'),
    path('admin-panel/transfer-window/', views.TransferWindowSettingsView.as_view(), name='transfer_window_settings'),
    path('admin-panel/transfer-window/pause/', views.TransferWindowPauseView.as_view(), name='transfer_window_pause'),
    path('admin-panel/transfer-window/resume/', views.TransferWindowResumeView.as_view(), name='transfer_window_resume'),
    path('admin-panel/transfer-window/archive/', views.TransferRecordArchiveCreateView.as_view(), name='transfer_record_archive_create'),
    path('admin-panel/transfer-records/', views.TransferRecordArchiveListView.as_view(), name='transfer_record_archive_list'),
    path('admin-panel/transfer-records/<int:pk>/', views.TransferRecordArchiveDetailView.as_view(), name='transfer_record_archive_detail'),
    path('admin-panel/accounts/', views.AccountAdminListView.as_view(), name='account_admin_list'),
    path('admin-panel/accounts/create/', views.AccountAdminCreateView.as_view(), name='account_admin_create'),
    path('admin-panel/accounts/import/', views.StudentCsvImportView.as_view(), name='account_admin_import'),
    path('admin-panel/accounts/bulk/deactivate/', views.AccountAdminBulkDeactivateView.as_view(), name='account_admin_bulk_deactivate'),
    path('admin-panel/accounts/bulk/reactivate/', views.AccountAdminBulkReactivateView.as_view(), name='account_admin_bulk_reactivate'),
    path('admin-panel/accounts/bulk/delete/confirm/', views.AccountAdminBulkDeleteConfirmView.as_view(), name='account_admin_bulk_delete_confirm'),
    path('admin-panel/accounts/bulk/delete/', views.AccountAdminBulkDeleteView.as_view(), name='account_admin_bulk_delete'),
    path('admin-panel/accounts/<int:pk>/promote-president/', views.AccountAdminPromotePresidentView.as_view(), name='account_admin_promote_president'),
    path('admin-panel/unassigned/accounts/', views.UnassignedAccountListView.as_view(), name='unassigned_account_list'),
    path('admin-panel/unassigned/assignment-records/', views.AssignmentRecordListView.as_view(), name='assignment_record_list'),
    path('admin-panel/unassigned/students/bulk/assign-club/', views.UnassignedStudentBulkAssignClubView.as_view(), name='unassigned_student_bulk_assign_club'),
    path('admin-panel/unassigned/students/<int:pk>/assign-club/', views.UnassignedStudentAssignClubView.as_view(), name='unassigned_student_assign_club'),
    path('admin-panel/teachers/', views.TeacherAdminListView.as_view(), name='teacher_admin_list'),
    path('admin-panel/teachers/create/', views.TeacherAdminCreateView.as_view(), name='teacher_admin_create'),
    path('admin-panel/teachers/<int:pk>/edit/', views.TeacherAdminUpdateView.as_view(), name='teacher_admin_edit'),
    path('admin-panel/teachers/<int:pk>/deactivate/', views.TeacherAdminDeactivateView.as_view(), name='teacher_admin_deactivate'),
    path('admin-panel/teachers/<int:pk>/reactivate/', views.TeacherAdminReactivateView.as_view(), name='teacher_admin_reactivate'),
    path('admin-panel/teachers/<int:pk>/delete/', views.TeacherAdminDeleteView.as_view(), name='teacher_admin_delete'),
    path('admin-panel/clubs/', views.ClubAdminListView.as_view(), name='club_admin_list'),
    path('admin-panel/clubs/create/', views.ClubAdminCreateView.as_view(), name='club_admin_create'),
    path('admin-panel/clubs/import/', views.ClubCsvImportView.as_view(), name='club_admin_import'),
    path('admin-panel/clubs/bulk/deactivate/', views.ClubAdminBulkDeactivateView.as_view(), name='club_admin_bulk_deactivate'),
    path('admin-panel/clubs/bulk/reactivate/', views.ClubAdminBulkReactivateView.as_view(), name='club_admin_bulk_reactivate'),
    path('admin-panel/clubs/bulk/delete/', views.ClubAdminBulkDeleteView.as_view(), name='club_admin_bulk_delete'),
    path('admin-panel/clubs/<int:pk>/edit/', views.ClubAdminUpdateView.as_view(), name='club_admin_edit'),
    path('admin-panel/clubs/<int:pk>/deactivate/', views.ClubAdminDeactivateView.as_view(), name='club_admin_deactivate'),
    path('admin-panel/clubs/<int:pk>/reactivate/', views.ClubAdminReactivateView.as_view(), name='club_admin_reactivate'),
    path('admin-panel/clubs/<int:club_pk>/members/<int:user_pk>/unassign/', views.ClubAdminMemberUnassignView.as_view(), name='club_admin_member_unassign'),
    path('admin-panel/clubs/<int:club_pk>/members/<int:user_pk>/replace-president/', views.ClubAdminReplacePresidentView.as_view(), name='club_admin_replace_president'),
    path('admin-panel/clubs/<int:pk>/delete/', views.ClubAdminDeleteView.as_view(), name='club_admin_delete'),
    path('admin-panel/students/', views.StudentAdminListView.as_view(), name='student_admin_list'),
    path('admin-panel/students/create/', views.StudentAdminCreateView.as_view(), name='student_admin_create'),
    path('admin-panel/students/bulk/deactivate/', views.StudentAdminBulkDeactivateView.as_view(), name='student_admin_bulk_deactivate'),
    path('admin-panel/students/bulk/reactivate/', views.StudentAdminBulkReactivateView.as_view(), name='student_admin_bulk_reactivate'),
    path('admin-panel/students/bulk/delete/confirm/', views.StudentAdminBulkDeleteConfirmView.as_view(), name='student_admin_bulk_delete_confirm'),
    path('admin-panel/students/bulk/delete/', views.StudentAdminBulkDeleteView.as_view(), name='student_admin_bulk_delete'),
    path('admin-panel/students/<int:pk>/edit/', views.StudentAdminUpdateView.as_view(), name='student_admin_edit'),
    path('admin-panel/students/<int:pk>/deactivate/', views.StudentAdminDeactivateView.as_view(), name='student_admin_deactivate'),
    path('admin-panel/students/<int:pk>/reactivate/', views.StudentAdminReactivateView.as_view(), name='student_admin_reactivate'),
    path('admin-panel/students/<int:pk>/delete/', views.StudentAdminDeleteView.as_view(), name='student_admin_delete'),
    path('admin-panel/students/<int:pk>/promote-president/', views.StudentAdminPromotePresidentView.as_view(), name='student_admin_promote_president'),
    path('admin-panel/students/import/', views.StudentCsvImportView.as_view(), name='student_admin_import'),
]
