# Generated by Django 4.2.30 on 2026-05-20

from django.db import migrations, models


def populate_student_class_and_seat(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    for number in range(1, 346):
        username = f"student{number:03d}"
        zero_based = number - 1
        class_name = str(101 + zero_based // 36)
        seat_number = zero_based % 36 + 1
        User.objects.filter(username=username).update(
            class_name=class_name,
            seat_number=seat_number,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_remove_user_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="class_name",
            field=models.CharField(blank=True, max_length=20, verbose_name="班級"),
        ),
        migrations.AddField(
            model_name="user",
            name="seat_number",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="座號"
            ),
        ),
        migrations.RunPython(
            populate_student_class_and_seat,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
