# Generated by Django 4.2.30 on 2026-04-15 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('orig_president_pending', '原社長審核中'), ('orig_teacher_pending', '原指導老師審核中'), ('new_president_pending', '新社長審核中'), ('new_teacher_pending', '新指導老師審核中'), ('admin_pending', '訓育組審核中'), ('approved', '已核准'), ('rejected', '已拒絕'), ('returned', '退回重選')], default='orig_president_pending', max_length=30, verbose_name='狀態')),
                ('reason', models.TextField(blank=True, verbose_name='轉社原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='申請時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成時間')),
                ('original_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_out_requests', to='clubs.club', verbose_name='原社團')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_requests', to=settings.AUTH_USER_MODEL, verbose_name='申請學生')),
                ('target_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_in_requests', to='clubs.club', verbose_name='目標社團')),
            ],
            options={
                'verbose_name': '轉社申請單',
                'verbose_name_plural': '轉社申請單',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_stage', models.CharField(max_length=30, verbose_name='審核階段')),
                ('result', models.CharField(choices=[('approve', '同意'), ('reject', '拒絕'), ('return', '退回重選')], max_length=10, verbose_name='審核結果')),
                ('comment', models.TextField(blank=True, verbose_name='審核意見')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='審核時間')),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='審核人')),
                ('transfer_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_logs', to='transfers.transferrequest', verbose_name='申請單')),
            ],
            options={
                'verbose_name': '審核紀錄',
                'verbose_name_plural': '審核紀錄',
                'ordering': ['-created_at'],
            },
        ),
    ]
