# Generated by Django 4.2.30 on 2026-06-04 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transfers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransferWindow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="轉社開始日期")),
                ("end_date", models.DateField(verbose_name="轉社結束日期")),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
            ],
            options={
                "verbose_name": "轉社期限設定",
                "verbose_name_plural": "轉社期限設定",
            },
        ),
    ]
