# Generated by Django 4.2.30 on 2026-06-04 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transfers", "0002_transferwindow"),
    ]

    operations = [
        migrations.AddField(
            model_name="transferwindow",
            name="is_paused",
            field=models.BooleanField(default=False, verbose_name="暫停轉社期"),
        ),
    ]
