# Generated by Django 4.2.30 on 2026-06-04 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("transfers", "0003_transferwindow_is_paused"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransferRecordArchive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="名稱")),
                ("start_date", models.DateField(verbose_name="開始日期")),
                ("end_date", models.DateField(verbose_name="結束日期")),
                (
                    "archived_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="儲存時間"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_transfer_record_archives",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="儲存者",
                    ),
                ),
                (
                    "transfer_window",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="record_archives",
                        to="transfers.transferwindow",
                        verbose_name="轉社期",
                    ),
                ),
            ],
            options={
                "verbose_name": "轉社紀錄批次",
                "verbose_name_plural": "轉社紀錄批次",
                "ordering": ["-archived_at"],
            },
        ),
        migrations.CreateModel(
            name="TransferRecordSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_name", models.CharField(max_length=150, verbose_name="學生")),
                (
                    "student_username",
                    models.CharField(max_length=150, verbose_name="帳號"),
                ),
                (
                    "student_id",
                    models.CharField(blank=True, max_length=20, verbose_name="學號"),
                ),
                (
                    "original_club_name",
                    models.CharField(max_length=100, verbose_name="原社團"),
                ),
                (
                    "target_club_name",
                    models.CharField(max_length=100, verbose_name="新社團"),
                ),
                ("status", models.CharField(max_length=30, verbose_name="狀態")),
                ("submitted_at", models.DateTimeField(verbose_name="申請時間")),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="核准或更新時間"
                    ),
                ),
                (
                    "approval_summary",
                    models.TextField(blank=True, verbose_name="審核摘要"),
                ),
                (
                    "archive",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="transfers.transferrecordarchive",
                        verbose_name="轉社紀錄批次",
                    ),
                ),
            ],
            options={
                "verbose_name": "轉社紀錄快照",
                "verbose_name_plural": "轉社紀錄快照",
                "ordering": ["submitted_at", "pk"],
            },
        ),
        migrations.AddConstraint(
            model_name="transferrecordarchive",
            constraint=models.UniqueConstraint(
                fields=("transfer_window", "start_date", "end_date"),
                name="unique_archive_per_transfer_window_period",
            ),
        ),
    ]
