# Generated by Django 4.2.30 on 2026-04-15 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='社團名稱')),
                ('description', models.TextField(blank=True, verbose_name='社團描述')),
                ('max_members', models.PositiveIntegerField(default=30, verbose_name='人數上限')),
                ('current_members', models.PositiveIntegerField(default=0, verbose_name='現有人數')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用中')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('president', models.ForeignKey(blank=True, limit_choices_to={'role': 'president'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leading_clubs', to=settings.AUTH_USER_MODEL, verbose_name='社長')),
                ('teacher', models.ForeignKey(blank=True, limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaching_clubs', to=settings.AUTH_USER_MODEL, verbose_name='指導老師')),
            ],
            options={
                'verbose_name': '社團',
                'verbose_name_plural': '社團',
                'ordering': ['name'],
            },
        ),
    ]
