# Generated by Django 4.2.30 on 2026-04-16 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("academic", "學術類"),
                    ("arts", "藝文類"),
                    ("performance", "藝能類"),
                    ("recreation", "康輔類"),
                    ("sports", "體育類"),
                ],
                max_length=20,
                verbose_name="類別",
            ),
        ),
        migrations.AddField(
            model_name="club",
            name="code",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                unique=True,
                verbose_name="社團代號",
            ),
        ),
        migrations.AddField(
            model_name="club",
            name="location",
            field=models.CharField(blank=True, max_length=100, verbose_name="社課場地"),
        ),
        migrations.AlterField(
            model_name="club",
            name="president",
            field=models.CharField(default="", max_length=50, verbose_name="社長"),
        ),
        migrations.AlterField(
            model_name="club",
            name="teacher",
            field=models.CharField(default="", max_length=50, verbose_name="指導老師"),
        ),
    ]
